### PR TITLE
Refactor home page with TailwindCSS and tsparticles

### PR DESCRIPTION
**Pull request by Abdalrhman-Almarakeby**
- Implement `(home)` Route Group.
- Update global CSS styles.
- Use TailwindCSS for styling, replacing css-in-js.
- Recreate animations using TailwindCSS and integrate tailwindcss-animation-delay plugin for animation delay.
- Replace animejs particles with tsparticles.
- Move particles logic into a custom hook.
- Extract components for background particles, heading, and links.

These changes aim to improve code structure and the styling of the home page.

### CODE REVIEW

**Comment by HermasTV** [comment]
There is an issue in the realtime face detection page, some components are no longer following the alignment structure, 
Trying zooming in and out of the page this happens :  

image


since the structure of the project changed there are too many things to follow up, catching where is the issue ,might take much time from my side. 

Overall , I like the new home page , We will keep it 👏

**Comment by HermasTV** [comment]
Your updates will be automatically deployed on this link : https://refactor-home-page.d15b5sjy8nooof.amplifyapp.com/

**Comment by HermasTV** [comment]
@Abdalrhman-Almarakeby Fixed for now. 

However we have mew  weird  issue, when I load a page, it loads the HTML only for a split second, then apply css,js. 
Will open an issue.

Approaved and Merged.

**Comment by Abdalrhman-Almarakeby** [comment]
@HermasTV Sorry for not responding earlier. I understand this weird issue and will work on it. However, I'm not sure if I'll be able to continue working on this project. I had some free time a few months ago, but not much now. Sorry about that. But don't worry, I will fix this issue because I won't leave the project with this bug.

I will fix it and create a PR for it ASAP.

**Pull request merged**
